"""
src/mok/routing/rsi.py

RSI — Routing Signal Integrator
"Recursive Self-Improvement" for the R0 rules router.

Reads completed trace logs (JSONL) and extracts new routing knowledge:
  - Which keywords correlate most strongly with which experts
  - Which experts were chosen at high confidence vs low confidence
  - Patterns that could be promoted into RulesRouter's compiled regexes

Nothing here mutates live state; it only produces *recommendations*.
The caller decides whether to apply them (human-in-the-loop by design).

Usage
-----
    from mok.routing.rsi import RoutingSignalIntegrator

    rsi = RoutingSignalIntegrator()
    rsi.ingest_log(Path("traces/runtime.jsonl"))
    report = rsi.report()           # human-readable markdown
    patches = rsi.keyword_patches() # {expert_name: [new_keywords]}

Phase gate: P4 (T2/T3 learned router) will consume patches automatically.
Until then, a developer reviews the output and edits router.py manually.
"""
from __future__ import annotations

import json
import re
from collections import Counter, defaultdict
from dataclasses import dataclass, field
from pathlib import Path
from typing import Iterator


# ---------------------------------------------------------------------------
# Domain types
# ---------------------------------------------------------------------------

@dataclass
class TraceRecord:
    """Minimal projection of a JSONL trace line."""
    request_id: str
    prompt: str
    route_expert: str
    route_confidence: float
    route_reason: str
    router_tier: str
    success: bool
    error_type: str | None = None


@dataclass
class KeywordSignal:
    """A candidate keyword extracted from traces."""
    token: str
    expert: str
    occurrences: int
    avg_confidence: float
    success_rate: float


@dataclass
class RSIReport:
    total_traces: int
    success_rate: float
    expert_call_counts: dict[str, int]
    tier_distribution: dict[str, int]
    error_breakdown: dict[str, int]
    top_signals: list[KeywordSignal]  # sorted by occurrences desc
    suggested_patterns: dict[str, str]  # expert -> suggested regex fragment

    def to_markdown(self) -> str:
        lines: list[str] = [
            "# RSI Report — Routing Signal Integrator",
            "",
            f"**Traces analysed:** {self.total_traces}",
            f"**Overall success rate:** {self.success_rate:.1%}",
            "",
            "## Expert call distribution",
        ]
        for expert, count in sorted(self.expert_call_counts.items(), key=lambda x: -x[1]):
            pct = count / max(self.total_traces, 1)
            lines.append(f"- `{expert}`: {count} ({pct:.1%})")

        lines += ["", "## Router tier distribution"]
        for tier, count in sorted(self.tier_distribution.items()):
            lines.append(f"- {tier}: {count}")

        if self.error_breakdown:
            lines += ["", "## Error breakdown"]
            for etype, count in sorted(self.error_breakdown.items(), key=lambda x: -x[1]):
                lines.append(f"- `{etype}`: {count}")

        lines += ["", "## Top keyword signals (candidate regex tokens)"]
        for sig in self.top_signals[:20]:
            lines.append(
                f"- `{sig.token}` → `{sig.expert}` "
                f"(n={sig.occurrences}, conf={sig.avg_confidence:.2f}, "
                f"success={sig.success_rate:.1%})"
            )

        if self.suggested_patterns:
            lines += ["", "## Suggested regex fragments to add to router.py"]
            for expert, pattern in sorted(self.suggested_patterns.items()):
                lines.append(f"- `{expert}`: `{pattern}`")

        lines += [
            "",
            "---",
            "_Generated by `mok.routing.rsi.RoutingSignalIntegrator`. "
            "Review before applying to RulesRouter._",
        ]
        return "\n".join(lines)


# ---------------------------------------------------------------------------
# Tokeniser — simple word splitter, no NLTK dependency
# ---------------------------------------------------------------------------

_STOP_WORDS: frozenset[str] = frozenset(
    "a an the is are was were be been being have has had do does did "
    "will would could should may might shall can i you he she it we they "
    "me him her us them my your his its our their what which who this that "
    "these those in on at by for with to of and or but not so if then "
    "when where how please just let me want need help make get set".split()
)

_TOKEN_RE = re.compile(r"[a-z][a-z0-9_]{2,}")  # min 3 chars, starts with letter


def _tokenise(text: str) -> list[str]:
    tokens = _TOKEN_RE.findall(text.lower())
    return [t for t in tokens if t not in _STOP_WORDS]


# ---------------------------------------------------------------------------
# Core integrator
# ---------------------------------------------------------------------------

class RoutingSignalIntegrator:
    """
    Ingests trace JSONL files and extracts routing knowledge.

    Obtaining new knowledge pipeline:
      1. ingest_log()   — parse raw JSONL events into TraceRecord objects
      2. _analyse()     — count keyword→expert co-occurrences, compute stats
      3. report()       — produce RSIReport with suggested regex patches
      4. keyword_patches() — machine-readable {expert: [tokens]} dict

    Thread-safety: not thread-safe; build one instance per analysis run.
    """

    # Only promote a token if it appears at least this many times
    MIN_OCCURRENCES: int = 3
    # And the expert choice must be consistent at least this often
    MIN_PURITY: float = 0.70
    # And average confidence must clear this bar
    MIN_CONFIDENCE: float = 0.75

    def __init__(self) -> None:
        self._records: list[TraceRecord] = []

    # ------------------------------------------------------------------
    # Ingestion
    # ------------------------------------------------------------------

    def ingest_log(self, path: Path) -> int:
        """Parse a JSONL trace file; return number of records ingested."""
        count = 0
        for record in self._parse_jsonl(path):
            self._records.append(record)
            count += 1
        return count

    def ingest_logs(self, *paths: Path) -> int:
        return sum(self.ingest_log(p) for p in paths)

    def clear(self) -> None:
        self._records.clear()

    @staticmethod
    def _parse_jsonl(path: Path) -> Iterator[TraceRecord]:
        if not path.exists():
            return
        with path.open(encoding="utf-8") as fh:
            for lineno, line in enumerate(fh, 1):
                line = line.strip()
                if not line:
                    continue
                try:
                    obj = json.loads(line)
                    yield TraceRecord(
                        request_id=str(obj.get("request_id", f"line-{lineno}")),
                        prompt=str(obj.get("prompt", "")),
                        route_expert=str(obj.get("route_expert", "unknown")),
                        route_confidence=float(obj.get("route_confidence", 0.0)),
                        route_reason=str(obj.get("route_reason", "")),
                        router_tier=str(obj.get("router_tier", "R0")),
                        success=bool(obj.get("success", True)),
                        error_type=obj.get("error_type") or None,
                    )
                except (json.JSONDecodeError, KeyError, TypeError, ValueError):
                    # Malformed line — skip silently; don't crash analysis
                    continue

    # ------------------------------------------------------------------
    # Analysis
    # ------------------------------------------------------------------

    def _analyse(self) -> tuple[
        dict[str, list[float]],          # token -> list of (confidence) where success
        dict[str, Counter[str]],          # token -> Counter{expert: count}
    ]:
        """
        For every token in every prompt, record which expert was chosen
        and the confidence.  Only successful traces contribute signal.
        """
        token_confidences: dict[str, list[float]] = defaultdict(list)
        token_experts: dict[str, Counter[str]] = defaultdict(Counter)

        for rec in self._records:
            if not rec.success:
                continue
            for token in set(_tokenise(rec.prompt)):  # set: one vote per prompt
                token_experts[token][rec.route_expert] += 1
                token_confidences[token].append(rec.route_confidence)

        return token_confidences, token_experts

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def report(self) -> RSIReport:
        """Analyse all ingested records and return a structured report."""
        total = len(self._records)
        successes = sum(1 for r in self._records if r.success)
        expert_counts: Counter[str] = Counter(r.route_expert for r in self._records)
        tier_counts: Counter[str] = Counter(r.router_tier for r in self._records)
        error_counts: Counter[str] = Counter(
            r.error_type for r in self._records if r.error_type
        )

        token_confidences, token_experts = self._analyse()

        signals: list[KeywordSignal] = []
        for token, expert_counter in token_experts.items():
            total_token = sum(expert_counter.values())
            if total_token < self.MIN_OCCURRENCES:
                continue
            top_expert, top_count = expert_counter.most_common(1)[0]
            purity = top_count / total_token
            if purity < self.MIN_PURITY:
                continue
            confs = token_confidences[token]
            avg_conf = sum(confs) / len(confs) if confs else 0.0
            if avg_conf < self.MIN_CONFIDENCE:
                continue
            # success_rate: fraction of all records with this token that succeeded
            all_with_token = sum(
                1 for r in self._records if token in _tokenise(r.prompt)
            )
            ok_with_token = sum(
                1 for r in self._records
                if token in _tokenise(r.prompt) and r.success
            )
            signals.append(KeywordSignal(
                token=token,
                expert=top_expert,
                occurrences=total_token,
                avg_confidence=avg_conf,
                success_rate=ok_with_token / max(all_with_token, 1),
            ))

        signals.sort(key=lambda s: (-s.occurrences, -s.avg_confidence))

        # Build suggested regex fragments: group tokens by target expert
        expert_tokens: dict[str, list[str]] = defaultdict(list)
        for sig in signals:
            expert_tokens[sig.expert].append(re.escape(sig.token))

        suggested_patterns: dict[str, str] = {
            expert: "|".join(tokens[:12])  # cap at 12 terms per expert
            for expert, tokens in expert_tokens.items()
            if tokens
        }

        return RSIReport(
            total_traces=total,
            success_rate=successes / max(total, 1),
            expert_call_counts=dict(expert_counts),
            tier_distribution=dict(tier_counts),
            error_breakdown=dict(error_counts),
            top_signals=signals,
            suggested_patterns=suggested_patterns,
        )

    def keyword_patches(self) -> dict[str, list[str]]:
        """
        Machine-readable output for automated pipeline (Phase 4+).
        Returns {expert_name: [token, ...]} for all signals that clear
        the quality thresholds.
        """
        _, token_experts = self._analyse()
        token_confidences, _ = self._analyse()

        patches: dict[str, list[str]] = defaultdict(list)
        for token, expert_counter in token_experts.items():
            total_token = sum(expert_counter.values())
            if total_token < self.MIN_OCCURRENCES:
                continue
            top_expert, top_count = expert_counter.most_common(1)[0]
            if top_count / total_token < self.MIN_PURITY:
                continue
            confs = token_confidences.get(token, [])
            avg_conf = sum(confs) / len(confs) if confs else 0.0
            if avg_conf < self.MIN_CONFIDENCE:
                continue
            patches[top_expert].append(token)

        return {k: sorted(v) for k, v in patches.items()}
